# meta_product_name: "MasterChef Junior 2"
# meta_title: "MasterChef Junior 2 - Participer et tentez de devenir le MasterChef Junior Maroc 2019 !"
# meta_description: "Relevant description"
# meta_image: "logo-MCJR.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards

meta_product_name: "Sanaat Bladi 8"
meta_title: "Sanaat Bladi 8 - Participer et tentez de remporter le trophée du meilleur apprenti artisan du Royaume !"
meta_description: "Sanaat Bladi 8 - Participer et tentez de remporter le trophée du meilleur apprenti artisan du Royaume !"
meta_image: "logo-SB.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
